import { Inter } from "next/font/google";
import "styles/globals.css";
import Layout from "components/layout";

// Font Awesomeの設定
import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
config.autoAddCss = false

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="{siteLang}">
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
